name: Run Java Code

on:
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Comma-separated arguments to pass to the Java application'
        required: true
        default: 'arg1,arg2,arg3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Choose your distribution here
          java-version: '11'

      - name: Compile Java code
        run: javac Application.java

      - name: Run Java code
        run: |
          # Split input arguments by comma into array using echo and tr
          ARGS=($(echo "${{ github.event.inputs.arguments }}" | tr ',' ' '))
          java Application "${ARGS[@]}"
